# Configuration for the project environment.

# Names of the isolated conda environments.
# Names of the isolated conda environments.
# env:
#   spleeter_env_name: "py38_spleeter"
#   madmom_env_name: "py39_madmom"
